app = "reminder-bot"
primary_region = "fra"

[env]
  TELEGRAM_BOT_TOKEN = "8130024965:AAEWM4Vu7lWggEwd11Wex1z3e4hTbLOKh9k"

[build]
  builder = "docker"

[[services]]
  internal_port = 8081
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 8081
    handlers = ["http"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
